debian/tmp/usr/bin/myproxy-change-pass-phrase
debian/tmp/usr/bin/myproxy-destroy
debian/tmp/usr/bin/myproxy-get-delegation
debian/tmp/usr/bin/myproxy-get-trustroots
debian/tmp/usr/bin/myproxy-info
debian/tmp/usr/bin/myproxy-init
debian/tmp/usr/bin/myproxy-logon
debian/tmp/usr/bin/myproxy-retrieve
debian/tmp/usr/bin/myproxy-store

debian/tmp/usr/share/man/man1/myproxy-change-pass-phrase.1
debian/tmp/usr/share/man/man1/myproxy-destroy.1
debian/tmp/usr/share/man/man1/myproxy-get-delegation.1
debian/tmp/usr/share/man/man1/myproxy-info.1
debian/tmp/usr/share/man/man1/myproxy-init.1
debian/tmp/usr/share/man/man1/myproxy-logon.1
debian/tmp/usr/share/man/man1/myproxy-retrieve.1
debian/tmp/usr/share/man/man1/myproxy-store.1
