'\" t
.\"     Title: globus-gridftp-password
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/31/2018
.\"    Manual: Grid Community Toolkit Manual
.\"    Source: Grid Community Toolkit 6
.\"  Language: English
.\"
.TH "GLOBUS\-GRIDFTP\-PAS" "8" "03/31/2018" "Grid Community Toolkit 6" "Grid Community Toolkit Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-gridftp-password \- creates an encrypted password to be used for an user of the Globus GridFTP server
.SH "SYNOPSYS"
.sp
globus\-gridftp\-password
.SH "DESCRIPTION"
.sp
Create encrypted user passwords to be used with the GridFTP server in case it is configured to use clear text password\&. However, this type of functionality is not recommended, unless the network is trusted\&.
.sp
The \fBglobus\-gridftp\-password\fR command asks for a password and generates a line in the same format as the standard password file (see file \fB/etc/passwd\fR)\&. Such a line can be appended to the password file used by the GridFTP server\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
% globus\-gridftp\-password >> pwfile
Password:
.fi
.if n \{\
.RE
.\}
.sp
Generates a password line for the current user and append it to file "pwfile"\&.
.SH "AUTHOR"
.sp
Initiative for Globus in Europe (IGE), http://www\&.ige\-project\&.eu
.SH "COPYRIGHT"
.sp
Copyright \(co 2012 Initiative for Globus in Europe (IGE)
.SH "SEE ALSO"
.sp
globus\-gridftp\-server(8)
