#!/bin/sh

set -e

if [ -x "/etc/init.d/globus-scheduler-event-generator" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d globus-scheduler-event-generator stop lsf || :
	else
		/etc/init.d/globus-scheduler-event-generator stop lsf || :
	fi
fi

#DEBHELPER#

if [ "$1" != "remove" -a "$1" != "purge" ]; then
	exit 0
fi

globus-gatekeeper-admin -d jobmanager-lsf-seg > /dev/null 2>&1 || :
globus-scheduler-event-generator-admin -d lsf > /dev/null 2>&1 || :

exit 0
